# -*- coding: utf-8 -*-
"""BnSentMix_Finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mZ-FgHrFg2TDqc9DppZpo70Vu-ULVjd

# BnSentMix: Fine-Tuning, Hyperparameter Tuning, and Soft-Voting Ensemble

Dataset: `aplycaebous/BnSentMix` (Alam et al., 2025, LoResLM Workshop @ COLING 2025)
Labels: 1=Positive, 2=Negative, 3=Neutral, 4=Mixed

Pipeline: Zero-Shot -> Five-Shot / Few-Shot (multi-seed, regularized standard fine-tuning + SetFit
contrastive few-shot) -> Full Fine-Tuning -> Hyperparameter Tuning (BanglaBERT, validation set only) ->
Soft-Voting Ensemble (BanglaBERT + XLM-RoBERTa + BanglishBERT) -> Full experiment logging.
"""

!pip -q install -U transformers datasets accelerate evaluate scikit-learn sentencepiece pandas numpy matplotlib setfit

import os, json, pickle, shutil, random
import numpy as np, pandas as pd, torch, torch.nn.functional as F
import matplotlib.pyplot as plt
from datasets import Dataset, load_dataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                           TrainingArguments, Trainer, pipeline, set_seed)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

SEED = 42
set_seed(SEED)
random.seed(SEED); np.random.seed(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

experiment_log = []
def log_experiment(model_name, setting, seed, config, metrics):
    experiment_log.append({"model": model_name, "setting": setting, "seed": seed,
                            "config": config, "metrics": metrics})

"""## 1. Load Dataset"""

raw = load_dataset("aplycaebous/BnSentMix")
print(raw)
df = raw["train"].to_pandas()
print(df.columns.tolist())
df.head()

# Explicitly assign column names based on dataset columns ['Sentence', 'Label']
text_col = "Sentence" if "Sentence" in df.columns else [c for c in df.columns if df[c].dtype == object][0]
label_col = "Label" if "Label" in df.columns else [c for c in df.columns if c != text_col][0]

print("text_col:", text_col, "| label_col:", label_col)

df = df[[text_col, label_col]].dropna().rename(columns={text_col: "text"})
df["label"] = pd.Categorical(df[label_col]).codes
label_names = list(pd.Categorical(df[label_col]).categories)
num_labels = len(label_names)
df = df[["text", "label"]].reset_index(drop=True)
print(label_names, num_labels)
print(df["label"].value_counts().sort_index())

"""## 2. Train / Validation / Test Split (70:15:15)"""

train_df, temp_df = train_test_split(df, test_size=0.30, stratify=df["label"], random_state=SEED)
val_df, test_df = train_test_split(temp_df, test_size=0.50, stratify=temp_df["label"], random_state=SEED)
print(len(train_df), len(val_df), len(test_df))
print("Train class distribution:\n", train_df["label"].value_counts().sort_index())

train_ds = Dataset.from_pandas(train_df.reset_index(drop=True))
val_ds = Dataset.from_pandas(val_df.reset_index(drop=True))
test_ds = Dataset.from_pandas(test_df.reset_index(drop=True))

"""## 3. Metrics
Both **weighted** and **macro** precision/recall/F1 are reported. With weighted averaging, recall
equals accuracy by construction, and both look inflated under class imbalance or majority-class
collapse. Macro-F1 treats every class equally and is the primary metric below.
"""

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, preds)
    p_w, r_w, f1_w, _ = precision_recall_fscore_support(labels, preds, average="weighted", zero_division=0)
    p_m, r_m, f1_m, _ = precision_recall_fscore_support(labels, preds, average="macro", zero_division=0)
    return {"accuracy": acc, "precision": p_w, "recall": r_w, "f1": f1_w,
            "precision_macro": p_m, "recall_macro": r_m, "f1_macro": f1_m}

def metrics_row(model_name, setting, seed, m, extra=None):
    row = {"model": model_name, "setting": setting, "seed": seed,
           "accuracy": m["eval_accuracy"], "precision": m["eval_precision"], "recall": m["eval_recall"], "f1": m["eval_f1"],
           "precision_macro": m["eval_precision_macro"], "recall_macro": m["eval_recall_macro"], "f1_macro": m["eval_f1_macro"]}
    if extra:
        row.update(extra)
    return row

"""## 4. Models"""

MODEL_LIST = {
    "mBERT": "bert-base-multilingual-cased",
    "XLM-RoBERTa": "xlm-roberta-base",
    "BanglaBERT": "csebuetnlp/banglabert",
    "BanglishBERT": "csebuetnlp/banglishbert",
    "DistilBERT": "distilbert-base-multilingual-cased",
    "BERT": "bert-base-uncased",
}
ENSEMBLE_MODELS = {k: MODEL_LIST[k] for k in ["BanglaBERT", "XLM-RoBERTa", "BanglishBERT"]}
MAX_LEN = 128

"""## 5. Fine-Tuning Function
Supports partial layer freezing (`freeze_base`), weight decay, label smoothing, and validation-based

early stopping (`patience`) on top of the base setup.

five-/few-shot fine-tuning

early stopping (selected on validation macro-F1)
"""

def tokenize_ds(ds, tokenizer):
    return ds.map(lambda x: tokenizer(x["text"], truncation=True, padding="max_length", max_length=MAX_LEN),
                  batched=True)

def freeze_base_layers(model, unfreeze_last_n=2):
    for _, p in model.named_parameters():
        p.requires_grad = False
    for n, p in model.named_parameters():
        if "classifier" in n or "pooler" in n:
            p.requires_grad = True
    layer_ids = {int(m.group(1)) for n, _ in model.named_parameters()
                 for m in [re.search(r"\.layer\.(\d+)\.", n)] if m}
    if layer_ids:
        keep = set(range(max(layer_ids) - unfreeze_last_n + 1, max(layer_ids) + 1))
        for n, p in model.named_parameters():
            m = re.search(r"\.layer\.(\d+)\.", n)
            if m and int(m.group(1)) in keep:
                p.requires_grad = True
    return model

def finetune(model_name, train_ds, val_ds, test_ds, num_labels, epochs=5, lr=2e-5, bs=16,
             tag="full", seed=SEED, keep_model=False, weight_decay=0.01, label_smoothing_factor=0.0,
             freeze_base=False, unfreeze_last_n=2, patience=None):
    set_seed(seed)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels).to(DEVICE)
    if freeze_base:
        model = freeze_base_layers(model, unfreeze_last_n)

    train_tok = tokenize_ds(train_ds, tokenizer)
    val_tok = tokenize_ds(val_ds, tokenizer)
    test_tok = tokenize_ds(test_ds, tokenizer)

    steps_per_epoch = max(1, len(train_tok) // bs)
    warmup_steps = max(1, int(0.1 * steps_per_epoch * epochs))

    out_dir = f"./out_{model_name.replace('/','_')}_{tag}_{seed}"
    args = TrainingArguments(
        output_dir=out_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=bs,
        per_device_eval_batch_size=bs,
        learning_rate=lr,
        weight_decay=weight_decay,
        label_smoothing_factor=label_smoothing_factor,
        warmup_steps=warmup_steps,
        eval_strategy="epoch",
        save_strategy="epoch" if patience else "no",
        save_total_limit=1,
        load_best_model_at_end=bool(patience),
        metric_for_best_model="f1_macro",
        greater_is_better=True,
        logging_steps=25,
        report_to="none",
        seed=seed,
    )
    callbacks = [EarlyStoppingCallback(early_stopping_patience=patience)] if patience else []
    trainer = Trainer(model=model, args=args, train_dataset=train_tok, eval_dataset=val_tok,
                       compute_metrics=compute_metrics, callbacks=callbacks)
    trainer.train()
    test_metrics = trainer.evaluate(test_tok)
    test_pred = trainer.predict(test_tok)
    y_true = test_pred.label_ids
    y_pred = np.argmax(test_pred.predictions, axis=-1)

    if os.path.exists(out_dir):
        shutil.rmtree(out_dir, ignore_errors=True)

    if keep_model:
        return test_metrics, trainer.state.log_history, (model, tokenizer), (y_true, y_pred)
    del model
    torch.cuda.empty_cache()
    return test_metrics, trainer.state.log_history, None, (y_true, y_pred)

"""## 6. Zero-Shot Classification"""

ZS_MODEL = "MoritzLaurer/mDeBERTa-v3-base-mnli-xnli"
candidate_labels = [str(l) for l in label_names]

def run_zero_shot(test_df, n=500):
    zs = pipeline("zero-shot-classification", model=ZS_MODEL, device=0 if DEVICE == "cuda" else -1)
    sample = test_df.sample(min(n, len(test_df)), random_state=SEED).reset_index(drop=True)
    preds = [candidate_labels.index(zs(t, candidate_labels)["labels"][0]) for t in sample["text"].tolist()]
    y_true = sample["label"].tolist()
    acc = accuracy_score(y_true, preds)
    p_w, r_w, f1_w, _ = precision_recall_fscore_support(y_true, preds, average="weighted", zero_division=0)
    p_m, r_m, f1_m, _ = precision_recall_fscore_support(y_true, preds, average="macro", zero_division=0)
    del zs
    torch.cuda.empty_cache()
    return {"eval_accuracy": acc, "eval_precision": p_w, "eval_recall": r_w, "eval_f1": f1_w,
            "eval_precision_macro": p_m, "eval_recall_macro": r_m, "eval_f1_macro": f1_m}

zero_shot_result = run_zero_shot(test_df)
print(zero_shot_result)
log_experiment("Zero-Shot(mDeBERTa-XNLI)", "zero-shot", None, {"n_sample": 500}, zero_shot_result)

"""## 7. N-Shot Sampling
Samples exactly `n_per_class` examples **per sentiment class** from the training set only.
"""

def sample_n_shot(train_df, n_per_class, seed):
    parts = [g.sample(min(n_per_class, len(g)), random_state=seed) for _, g in train_df.groupby("label")]
    sampled = pd.concat(parts).reset_index(drop=True)
    counts = sampled["label"].value_counts().sort_index()
    assert (counts == n_per_class).all(), f"Class imbalance in {n_per_class}-shot sample: {counts.to_dict()}"
    return sampled

SEEDS = [13, 42, 100]
print("five-shot check:\n", sample_n_shot(train_df, 5, 13)["label"].value_counts().sort_index())
print("few-shot check:\n", sample_n_shot(train_df, 20, 13)["label"].value_counts().sort_index())

"""## 8. Five-Shot / Few-Shot (multi-seed, regularized) and Full Fine-Tuning
Five-shot (5/class) and few-shot (20/class) use a regularized config for standard fine-tuning:

only the top 2 transformer layers + head are trainable (`freeze_base=True`), lower learning rate, weight decay, label smoothing, and early stopping on validation macro-F1.

Each is repeated over `SEEDS`. Full fine-tuning uses the entire training set, unfrozen, single seed.
"""

all_results = []
loss_curves = {}
raw_predictions = {}

SHOT_SETTINGS = [("five-shot", 5, 15, 4), ("few-shot", 20, 10, 8)]

for name, model_name in MODEL_LIST.items():
    for setting, n_per_class, epochs, bs in SHOT_SETTINGS:
        for seed in SEEDS:
            shot_df = sample_n_shot(train_df, n_per_class, seed=seed)
            shot_ds = Dataset.from_pandas(shot_df.reset_index(drop=True))
            print(f"=== {name} | {setting} | seed={seed} ===")
            m, lh, _, (yt, yp) = finetune(model_name, shot_ds, val_ds, test_ds, num_labels,
                                           epochs=epochs, lr=2e-5, bs=bs,
                                           tag=f"{setting}_{seed}", seed=seed)
            cfg = {"n_per_class": n_per_class, "epochs": epochs, "bs": bs, "lr": 2e-5}
            log_experiment(name, setting, seed, cfg, m)
            all_results.append(metrics_row(name, setting, seed, m, extra=cfg))
            raw_predictions[(name, setting, seed)] = (yt, yp)

    print(f"=== {name} | full | seed={SEED} ===")
    mfull, lhfull, _, (ytf, ypf) = finetune(model_name, train_ds, val_ds, test_ds, num_labels,
                                             epochs=5, lr=2e-5, bs=32, tag="full", seed=SEED)
    cfg = {"n_per_class": None, "epochs": 5, "bs": 32, "lr": 2e-5}
    log_experiment(name, "full", SEED, cfg, mfull)
    all_results.append(metrics_row(name, "full", SEED, mfull, extra=cfg))
    loss_curves[name] = lhfull
    raw_predictions[(name, "full", SEED)] = (ytf, ypf)

all_results_df = pd.DataFrame(all_results)
all_results_df.to_csv("all_results_raw_per_seed.csv", index=False)
all_results_df.head()

"""## 8b. SetFit: Contrastive Few-Shot Learning
SetFit (Tunstall et al., 2022) is the established approach for N<50 examples/class: it fine-tunes a Sentence-Transformer body on contrastive pairs generated from the few-shot examples, then fits a lightweight classification head, without any prompt or large-scale generative model. It typically
outperforms standard cross-entropy fine-tuning of a full transformer at this data scale.
"""

import wandb

wandb.login()

from setfit import (
    SetFitModel,
    Trainer as SFTrainer,
    TrainingArguments as SFTrainingArguments
)

SETFIT_BASE = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"


def run_setfit(
    shot_df,
    test_df,
    seed,
    setting,
    num_iterations=20,
    epochs=1
):
    set_seed(seed)

    model = SetFitModel.from_pretrained(SETFIT_BASE)

    train_dataset = Dataset.from_pandas(
        shot_df[["text", "label"]].reset_index(drop=True),
        preserve_index=False
    )

    args = SFTrainingArguments(
        batch_size=16,
        num_epochs=epochs,
        num_iterations=num_iterations,
        seed=seed,

        # Already logged in -> no API key code needed
        report_to="wandb",
        run_name=f"SetFit-{setting}-seed-{seed}",

        save_strategy="no"
    )

    trainer = SFTrainer(
        model=model,
        args=args,
        train_dataset=train_dataset,
        metric="accuracy"
    )

    trainer.train()

    # Prediction
    y_pred = np.asarray(
        model.predict(test_df["text"].tolist())
    )

    y_true = test_df["label"].to_numpy()

    # Metrics
    acc = accuracy_score(y_true, y_pred)

    p_w, r_w, f1_w, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    p_m, r_m, f1_m, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )

    m = {
        "eval_accuracy": acc,
        "eval_precision": p_w,
        "eval_recall": r_w,
        "eval_f1": f1_w,
        "eval_precision_macro": p_m,
        "eval_recall_macro": r_m,
        "eval_f1_macro": f1_m
    }

    # Cleanup
    del trainer
    del model

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return m, (y_true, y_pred)


# ============================================================
# Run SetFit experiments
# ============================================================

for setting, n_per_class in [
    ("five-shot", 5),
    ("few-shot", 20)
]:
    for seed in SEEDS:

        shot_df = sample_n_shot(
            train_df,
            n_per_class,
            seed=seed
        )

        print("\n" + "=" * 70)
        print(
            f"SetFit | {setting} | "
            f"{n_per_class} samples/class | seed={seed}"
        )
        print("=" * 70)

        m, (yt, yp) = run_setfit(
            shot_df=shot_df,
            test_df=test_df,
            seed=seed,
            setting=setting
        )

        cfg = {
            "n_per_class": n_per_class,
            "base_model": SETFIT_BASE
        }

        log_experiment(
            "SetFit",
            setting,
            seed,
            cfg,
            m
        )

        all_results.append(
            metrics_row(
                "SetFit",
                setting,
                seed,
                m,
                extra=cfg
            )
        )

        raw_predictions[
            ("SetFit", setting, seed)
        ] = (yt, yp)


# ============================================================
# Save results
# ============================================================

all_results_df = pd.DataFrame(all_results)

all_results_df.to_csv(
    "all_results_raw_per_seed.csv",
    index=False
)

all_results_df.head()

"""## 9. Aggregate Results (mean +/- std over seeds) and Collapse Diagnostics"""

metric_cols = ["accuracy", "precision", "recall", "f1", "precision_macro", "recall_macro", "f1_macro"]
agg_df = all_results_df.groupby(["model", "setting"])[metric_cols].agg(["mean", "std"])
agg_df.columns = [f"{m}_{s}" for m, s in agg_df.columns]
agg_df = agg_df.fillna(0.0).reset_index()
agg_df.to_csv("all_results_aggregated.csv", index=False)
agg_df

def fmt_mean_std(row, metric):
    return f"{row[metric+'_mean']:.3f} +/- {row[metric+'_std']:.3f}"

summary_tbl = agg_df.copy()
for metric in ["f1_macro", "accuracy", "f1"]:
    summary_tbl[metric] = summary_tbl.apply(lambda r: fmt_mean_std(r, metric), axis=1)
summary_tbl = summary_tbl[["model", "setting", "accuracy", "f1", "f1_macro"]]
print(summary_tbl.to_string(index=False))

example_key = ("BanglaBERT", "five-shot", SEEDS[0])
yt, yp = raw_predictions[example_key]
cm = confusion_matrix(yt, yp, labels=list(range(num_labels)))
print(f"Confusion matrix for {example_key} (rows=true, cols=pred):")
print(pd.DataFrame(cm, index=label_names, columns=label_names))
print("\nPredicted class distribution:", pd.Series(yp).value_counts().sort_index().to_dict())
print("True class distribution:     ", pd.Series(yt).value_counts().sort_index().to_dict())
print("\nIf accuracy/recall stay high while macro-F1 stays low here, the model is still collapsing")
print("toward the majority class (Neutral) despite freezing/early stopping; consider SetFit's results")
print("for comparison, or increase n_per_class if the paper's shot budget allows it.")

"""## 10. Comparative Analysis Across Models and Learning Settings (macro-F1)"""

model_names = list(MODEL_LIST.keys()) + ["SetFit"]
settings_order = ["five-shot", "few-shot", "full"]

def pivot_mean(metric):
    return agg_df.pivot(index="model", columns="setting", values=f"{metric}_mean").reindex(columns=settings_order)

def pivot_std(metric):
    return agg_df.pivot(index="model", columns="setting", values=f"{metric}_std").reindex(columns=settings_order)

comp_f1_macro = pivot_mean("f1_macro").round(4)
comp_f1_macro_std = pivot_std("f1_macro").round(4)
comp_acc = pivot_mean("accuracy").round(4)
comp_f1_macro["gain_full_vs_5shot"] = comp_f1_macro["full"] - comp_f1_macro["five-shot"]
comp_f1_macro = comp_f1_macro.sort_values("full", ascending=False, na_position="last")
comp_acc = comp_acc.loc[comp_f1_macro.index]

print("Macro-F1 (mean):\n", comp_f1_macro, "\n")
print("Macro-F1 (std):\n", comp_f1_macro_std.loc[comp_f1_macro.index], "\n")
print("Accuracy (mean):\n", comp_acc)

best_model = comp_f1_macro["full"].idxmax()
print(f"\nBest model (full fine-tuning): {best_model} | macro-F1={comp_f1_macro.loc[best_model,'full']:.4f}")
print(f"Zero-shot baseline macro-F1: {zero_shot_result['eval_f1_macro']:.4f}")
best_5shot = comp_f1_macro["five-shot"].idxmax()
print(f"Best five-shot model: {best_5shot} | macro-F1={comp_f1_macro.loc[best_5shot,'five-shot']:.4f}")

"""## 11. Comparative Graphs"""

plt.rcParams.update({"font.family": "serif", "font.size": 12, "axes.linewidth": 1.0,
                      "axes.edgecolor": "black", "figure.dpi": 300})

plot_models = comp_f1_macro.index.tolist()
x = np.arange(len(plot_models))
width = 0.25
colors = ["#4C72B0", "#DD8452", "#55A868"]

fig, ax = plt.subplots(figsize=(9, 5.5))
for i, setting in enumerate(settings_order):
    means = comp_f1_macro.loc[plot_models, setting].values
    stds = comp_f1_macro_std.loc[plot_models, setting].values
    ax.bar(x + (i - 1) * width, means, width, yerr=stds, capsize=3,
           label=setting.replace("-", " ").title(), color=colors[i], edgecolor="black", linewidth=0.6)

ax.axhline(zero_shot_result["eval_f1_macro"], color="black", linestyle="--", linewidth=1.2, label="Zero-Shot Baseline")
ax.set_xticks(x)
ax.set_xticklabels(plot_models, rotation=20, ha="right")
ax.set_ylabel("Macro F1-Score")
ax.set_ylim(0, 1)
ax.set_title("Macro-F1 Comparison Across Models and Learning Settings on BnSentMix")
ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(1.01, 1))
ax.grid(axis="y", linestyle=":", alpha=0.6)
plt.tight_layout()
plt.savefig("bnsentmix_comparative_f1_macro.pdf", bbox_inches="tight")
plt.savefig("bnsentmix_comparative_f1_macro.png", dpi=300, bbox_inches="tight")
plt.show()

shot_counts = {"five-shot": 5 * num_labels, "few-shot": 20 * num_labels, "full": len(train_df)}

fig, ax = plt.subplots(figsize=(7.5, 5.5))
for m in plot_models:
    ys = [comp_f1_macro.loc[m, s] if s in comp_f1_macro.columns else np.nan for s in settings_order]
    ax.plot([shot_counts[s] for s in settings_order], ys, marker="o", linewidth=1.8, label=m)
ax.axhline(zero_shot_result["eval_f1_macro"], color="black", linestyle="--", linewidth=1.2, label="Zero-Shot Baseline")
ax.set_xscale("log")
ax.set_xlabel("Number of Training Examples (log scale)")
ax.set_ylabel("Macro F1-Score")
ax.set_title("Sample Efficiency: Macro-F1 vs. Training Set Size")
ax.legend(frameon=False, fontsize=9, loc="lower right")
ax.grid(True, which="both", linestyle=":", alpha=0.5)
plt.tight_layout()
plt.savefig("bnsentmix_sample_efficiency.pdf", bbox_inches="tight")
plt.savefig("bnsentmix_sample_efficiency.png", dpi=300, bbox_inches="tight")
plt.show()

fig, ax = plt.subplots(figsize=(7.5, 5.5))
vals = comp_f1_macro[settings_order].values
im = ax.imshow(vals, cmap="Blues", vmin=0, vmax=1, aspect="auto")
ax.set_xticks(range(len(settings_order)))
ax.set_xticklabels([s.replace("-", " ").title() for s in settings_order])
ax.set_yticks(range(len(plot_models)))
ax.set_yticklabels(plot_models)
for i in range(len(plot_models)):
    for j in range(len(settings_order)):
        v = vals[i, j]
        txt = "n/a" if np.isnan(v) else f"{v:.3f}"
        ax.text(j, i, txt, ha="center", va="center",
                color="white" if (not np.isnan(v) and v > 0.5) else "black", fontsize=10)
ax.set_title("Macro-F1 Heatmap: Models vs. Learning Settings")
fig.colorbar(im, ax=ax, label="Macro F1-Score", fraction=0.046, pad=0.04)
plt.tight_layout()
plt.savefig("bnsentmix_f1_heatmap.pdf", bbox_inches="tight")
plt.savefig("bnsentmix_f1_heatmap.png", dpi=300, bbox_inches="tight")
plt.show()

"""## 12. Hyperparameter Tuning (BanglaBERT, validation set only)
Test set is never used for tuning: `finetune(..., val_ds, val_ds, ...)` passes `val_ds` in place of
`test_ds`, so reported metrics are validation-set metrics only.
"""

HP_GRID = [
    {"lr": 1e-5, "bs": 16, "epochs": 5},
    {"lr": 2e-5, "bs": 16, "epochs": 5},
    {"lr": 3e-5, "bs": 16, "epochs": 5},
    {"lr": 2e-5, "bs": 32, "epochs": 5},
    {"lr": 2e-5, "bs": 16, "epochs": 8},
    {"lr": 5e-5, "bs": 32, "epochs": 3},
]

hp_rows = []
for i, hp in enumerate(HP_GRID):
    print(f"=== HPO trial {i}: {hp} ===")
    m, _, _, _ = finetune("csebuetnlp/banglabert", train_ds, val_ds, val_ds, num_labels,
                           epochs=hp["epochs"], lr=hp["lr"], bs=hp["bs"], tag=f"hpo_{i}", seed=SEED)
    log_experiment("BanglaBERT", "hpo_trial", SEED, hp, m)
    hp_rows.append({"trial": i, **hp, "val_f1_macro": m["eval_f1_macro"], "val_accuracy": m["eval_accuracy"]})

hp_df = pd.DataFrame(hp_rows).sort_values("val_f1_macro", ascending=False).reset_index(drop=True)
hp_df.to_csv("hpo_banglabert_trials.csv", index=False)
best_hp = hp_df.iloc[0][["lr", "bs", "epochs"]].to_dict()
best_hp["bs"] = int(best_hp["bs"]); best_hp["epochs"] = int(best_hp["epochs"])
print(hp_df)
print("Best HP config (by validation macro-F1):", best_hp)

"""## 13. Validate Single Models with Tuned Config (BanglaBERT, XLM-RoBERTa, BanglishBERT)
Each ensemble candidate is retrained on the full training set with `best_hp`
"""

ensemble_assets = {}
tuned_single_rows = []

for name, model_name in ENSEMBLE_MODELS.items():
    print(f"=== {name}: tuned full fine-tune ===")
    m, lh, assets, (yt, yp) = finetune(model_name, train_ds, val_ds, test_ds, num_labels,
                                        epochs=best_hp["epochs"], lr=best_hp["lr"], bs=best_hp["bs"],
                                        tag="tuned_full", seed=SEED, keep_model=True)
    log_experiment(name, "full_tuned", SEED, best_hp, m)
    tuned_single_rows.append(metrics_row(name, "full_tuned", SEED, m))
    ensemble_assets[name] = assets
    loss_curves[name + "_tuned"] = lh

tuned_single_df = pd.DataFrame(tuned_single_rows).sort_values("f1_macro", ascending=False).reset_index(drop=True)
tuned_single_df.to_csv("tuned_single_model_results.csv", index=False)
tuned_single_df

"""## 14. Soft-Voting Ensemble (BanglaBERT + XLM-RoBERTa + BanglishBERT)
Voting weights are grid-searched on the **validation set only**; the test set is consider exactly once, for the final reported ensemble score.
"""

def get_probs(model, tokenizer, ds):
    tok = tokenize_ds(ds, tokenizer)
    cols = [c for c in ["input_ids", "attention_mask", "token_type_ids"] if c in tok.column_names]
    tok.set_format(type="torch", columns=cols)
    loader = torch.utils.data.DataLoader(tok, batch_size=32)
    model.eval()
    probs = []
    with torch.no_grad():
        for batch in loader:
            batch = {k: v.to(DEVICE) for k, v in batch.items()}
            logits = model(**batch).logits
            probs.append(F.softmax(logits, dim=-1).cpu().numpy())
    return np.concatenate(probs, axis=0)

names = list(ensemble_assets.keys())
val_probs = {n: get_probs(m, tok, val_ds) for n, (m, tok) in ensemble_assets.items()}
test_probs = {n: get_probs(m, tok, test_ds) for n, (m, tok) in ensemble_assets.items()}
val_labels = np.array(val_ds["label"])
test_labels = np.array(test_ds["label"])

def macro_f1_from_probs(weighted_probs, y_true):
    preds = np.argmax(weighted_probs, axis=-1)
    return precision_recall_fscore_support(y_true, preds, average="macro", zero_division=0)[2]

weight_grid = np.round(np.arange(0.0, 1.05, 0.1), 2)
best_w, best_val_f1 = None, -1
for w1 in weight_grid:
    for w2 in weight_grid:
        w3 = round(1 - w1 - w2, 2)
        if w3 < 0 or w3 > 1:
            continue
        weighted = w1 * val_probs[names[0]] + w2 * val_probs[names[1]] + w3 * val_probs[names[2]]
        f1 = macro_f1_from_probs(weighted, val_labels)
        if f1 > best_val_f1:
            best_val_f1 = f1
            best_w = (w1, w2, w3)

weight_dict = dict(zip(names, best_w))
print(f"Best weights (validation macro-F1={best_val_f1:.4f}):", weight_dict)
log_experiment("Ensemble(BanglaBERT+XLM-R+BanglishBERT)", "weight_search", SEED,
                {"weight_grid_step": 0.1}, {"val_macro_f1": best_val_f1, "weights": weight_dict})

w1, w2, w3 = best_w
ensemble_test_probs = w1 * test_probs[names[0]] + w2 * test_probs[names[1]] + w3 * test_probs[names[2]]
ensemble_preds = np.argmax(ensemble_test_probs, axis=-1)

acc = accuracy_score(test_labels, ensemble_preds)
p_w, r_w, f1_w, _ = precision_recall_fscore_support(test_labels, ensemble_preds, average="weighted", zero_division=0)
p_m, r_m, f1_m, _ = precision_recall_fscore_support(test_labels, ensemble_preds, average="macro", zero_division=0)

ensemble_result = {"model": "Soft-Voting Ensemble", "weights": weight_dict, "accuracy": acc,
                    "precision": p_w, "recall": r_w, "f1": f1_w,
                    "precision_macro": p_m, "recall_macro": r_m, "f1_macro": f1_m}
log_experiment("Ensemble(BanglaBERT+XLM-R+BanglishBERT)", "soft_voting_test", SEED,
                {"weights": weight_dict}, ensemble_result)

print(ensemble_result)

best_single = tuned_single_df.iloc[0]
print(f"\nBest single tuned model: {best_single['model']} | macro-F1={best_single['f1_macro']:.4f}")
print(f"Soft-voting ensemble:    macro-F1={f1_m:.4f}")
print(f"Improvement over best single model: {f1_m - best_single['f1_macro']:+.4f}")

"""## 15. Save Results, Configs, and Logs for All Experiments"""

os.makedirs("results", exist_ok=True)

all_results_df.to_csv("results/all_results_raw_per_seed.csv", index=False)
agg_df.to_csv("results/all_results_aggregated_mean_std.csv", index=False)
hp_df.to_csv("results/hpo_banglabert_trials.csv", index=False)
tuned_single_df.to_csv("results/tuned_single_model_results.csv", index=False)
pd.DataFrame([ensemble_result]).to_csv("results/ensemble_result.csv", index=False)

with open("results/experiment_log.json", "w") as f:
    json.dump(experiment_log, f, indent=2, default=str)

with open("results/best_hp_config.json", "w") as f:
    json.dump(best_hp, f, indent=2)

with open("results/full_state.pkl", "wb") as f:
    pickle.dump({"all_results_df": all_results_df, "agg_df": agg_df, "hp_df": hp_df,
                 "tuned_single_df": tuned_single_df, "ensemble_result": ensemble_result,
                 "zero_shot_result": zero_shot_result, "loss_curves": loss_curves,
                 "experiment_log": experiment_log}, f)

for fig_file in ["bnsentmix_comparative_f1_macro.pdf", "bnsentmix_comparative_f1_macro.png",
                  "bnsentmix_sample_efficiency.pdf", "bnsentmix_sample_efficiency.png",
                  "bnsentmix_f1_heatmap.pdf", "bnsentmix_f1_heatmap.png"]:
    if os.path.exists(fig_file):
        shutil.copy(fig_file, os.path.join("results", fig_file))

shutil.make_archive("bnsentmix_results", "zip", "results")
print("All results, configs, and logs saved to results/ and bnsentmix_results.zip")

try:
    from google.colab import files
    files.download("bnsentmix_results.zip")
except Exception:
    pass